[build]
  publish = "dist"
  command = "bun run build"

[build.environment]
  NODE_VERSION = "20.19.0"

[dev]
  command = "bun run dev"
  port = 8888
  targetPort = 4321
  publish = "dist"
  autoLaunch = false